wandb_version: 1

data_path:
  desc: null
  value: data/FB15K-237
process_path:
  desc: null
  value: /data/pj20/lamake_data
dataset:
  desc: null
  value: FB15K-237
hierarchy_type:
  desc: null
  value: seed
do_train:
  desc: null
  value: true
do_valid:
  desc: null
  value: true
do_test:
  desc: null
  value: true
evaluate_train:
  desc: null
  value: false
countries:
  desc: null
  value: false
regions:
  desc: null
  value: null
double_entity_embedding:
  desc: null
  value: false
double_relation_embedding:
  desc: null
  value: false
negative_sample_size:
  desc: null
  value: 256
hidden_dim:
  desc: null
  value: 1024
gamma:
  desc: null
  value: 24.0
negative_adversarial_sampling:
  desc: null
  value: true
adversarial_temperature:
  desc: null
  value: 1.0
batch_size:
  desc: null
  value: 1024
regularization:
  desc: null
  value: 0.0
test_batch_size:
  desc: null
  value: 16
model:
  desc: null
  value: TransE
rho:
  desc: null
  value: 0.5
lambda_1:
  desc: null
  value: 0.5
lambda_2:
  desc: null
  value: 0.5
lambda_3:
  desc: null
  value: 0.5
zeta_1:
  desc: null
  value: 0.5
zeta_2:
  desc: null
  value: 0.5
zeta_3:
  desc: null
  value: 0.5
num_epochs:
  desc: null
  value: 1000
early_stop:
  desc: null
  value: 10
cuda:
  desc: null
  value: true
uni_weight:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.0001
cpu_num:
  desc: null
  value: 10
init_checkpoint:
  desc: null
  value: null
save_path:
  desc: null
  value: /data/pj20/lamake_data/FB15K-237/checkpoints/TransE
max_steps:
  desc: null
  value: 150000
warm_up_steps:
  desc: null
  value: null
save_checkpoint_steps:
  desc: null
  value: 10000
valid_steps:
  desc: null
  value: 10000
log_steps:
  desc: null
  value: 100
test_log_steps:
  desc: null
  value: 1000
nentity:
  desc: null
  value: 0
nrelation:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.16.6
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714957934.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 105
      3:
      - 1
      - 16
      - 23
      - 61
      4: 3.8.13
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
